version: '3.7'

services:
  mongodb:
    container_name: mongo-stonecase
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
      args: 
        DB_IMAGE: mongo:latest
    ports:
      - 27017:27017

  db_seed:
    build:
      context: .
      dockerfile: docker/db/seed/Dockerfile
      args:
        DB_IMAGE: mongo:latest
    links:
      - mongodb
    depends_on:
      - mongodb
